# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:
  encoders:
    AppBundle\Entity\User:
      algorithm: bcrypt

  # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
  providers:
    in_memory:
      memory: ~
    token_auth:
      entity:
        class: AppBundle:User
        property: email

  firewalls:
    # disables authentication for assets and the profiler, adapt it according to your needs

    # dev:
    #   # pattern: ^/(_(profiler|wdt)|css|images|js)/
    #   security: false
      

    api:
      pattern: ^/api/
      stateless: true
      guard:
        authenticators:
          - AppBundle\JWT\JWTAuthenticator
      provider: token_auth

    
      

    main:
      anonymous: ~
      json_login: 
        check_path: login
        username_path: security.credentials.email
        password_path: security.credentials.password 
      provider: token_auth



      # logout:
      #   path: /logout
      #   target: /
      #   invalidate_session: true
        
        
        
       

  access_control:
    - { path: "^/login", roles: "ROLE_PUBLIC" }
    - { path: "^/api/admin", roles: "ROLE_ADMIN" }

    # activate different ways to authenticate

    # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
    #http_basic: ~

    # https://symfony.com/doc/current/security/form_login_setup.html
    #form_login: ~

