<?php

namespace OutagesBundle\Repository;

/**
 * Outage_CommentsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Outage_CommentsRepository extends \Doctrine\ORM\EntityRepository
{

    public function fetchComments(string $outage_id, int $page)
    {
        // SELECT * from sdu_orders  WHERE order_status ='1' UNION SELECT * from mdu_orders where order_status='1' order by  creation_date DESC
        // $outage_status = 0;
        // switch ($type) {
        //     case 'open':
        //         $outage_status = 1;
        //         # code...
        //         break;
        //     case 'closed':
        //         $outage_status = 2;

        //         # code...
        //         break;
        // }

        // $outage_status = 1;
        $query_builder = $this->createQueryBuilder('c');
        $query_builder->select('
            c.commentId as comment_id,
            c.commentDate as comment_date,
            c.comment ,
            c.commentBy as comment_by,
            c.outage 
           
            
           ');

        // $query_builder->innerJoin('OutagesBundle\Entity\Outage_Comments', 'c', 'WITH', 'c.outageId=c.outage');
        $query_builder->where($query_builder->expr()->eq('c.outage', ':outage_id'));
        $query_builder->setParameter('outage_id', $outage_id);
        $result = $query_builder->getQuery()->getResult();




        return $result;
    }
}
