<?php

namespace UserBundle\Repository;

/**
 * RolesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RolesRepository extends \Doctrine\ORM\EntityRepository
{

    public function fetchAllRoles()
    {
        $query_builder = $this->createQueryBuilder('r');
        $query_builder->select('r.id as role_id,
        r.roleName as role_name');
        $query_builder->where($query_builder->expr()->isNotNull('r.id'));
        $result = $query_builder->getQuery()->getResult();
        return $result;
    }
}
