<?php

namespace UserBundle\Repository;

/**
 * TechniciansRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TechniciansRepository extends \Doctrine\ORM\EntityRepository
{

    public function fetchTechnicians()
    {
        $query_builder = $this->createQueryBuilder('t');
        $query_builder->select('t.id as technician_id,
        t.techName as tech_name,
        t.techSurname as tech_surname,
        t.techEmail as tech_email,
        t.contactNumber as tech_contact');
        $query_builder ->where($query_builder->expr()->isNotNull('t.id'));
        $result = $query_builder->getQuery()->getResult();
        return $result;
    }
}
