lexik_jwt_authentication:
    secret_key: '../config/jwt/private.pem' # required for token creation
    public_key: '../config/jwt/public.pem'  # required for token verification
    pass_phrase:    'mafdhklkjkn234kas' # required for token creation, usage of an environment variable is recommended
    token_ttl: 5600