nelmio_cors:
    defaults:
        allow_credentials: true
        allow_origin: ['https://localhost:4200']
        allow_headers: ['Content-Type', 'Access-Control-Allow-Headers', 'Authorization',' X-Requested-With']
        allow_methods: ['POST', 'PUT', 'GET', 'DELETE','PATCH']
        # expose_headers: ['link']
        max_age: 3600
        origin_regex: false
    paths:
        '/login': ~
            # origin_regex: true
            # allow_origin: ['https://localhost:4200']
            # allow_headers: ['Accept', 'Content-Type','Authorization','X-Requested-With']
            # allow_methods: ['POST', 'PUT', 'GET', 'DELETE']
            # max_age: 3600
            # keep-alive: true
            