<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerIivul0r\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerIivul0r/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerIivul0r.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerIivul0r\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerIivul0r\appDevDebugProjectContainer([
    'container.build_hash' => 'Iivul0r',
    'container.build_id' => '962a790b',
    'container.build_time' => 1691221964,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerIivul0r');
